require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Sandi Metz's Rules (https://thoughtbot.com/blog/sandi-metz-rules-for-developers)
Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 5

Metrics/ParameterLists:
  Max: 4

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Max: 100

# Project-specific overrides
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/AbcSize:
  Max: 15

Metrics/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true 