AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Max: 25

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/ParameterLists:
  Max: 4

Style/GuardClause:
  Enabled: true 